project_name: locker
version: 2

release:
  github:
    owner: bgrewell
    name: locker

builds:
  - id: locker
    main: ./cmd/locker/main.go
    binary: locker
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-X 'main.version={{.Version}}'"
      - "-X 'main.builddate={{.Date}}'"
      - "-X 'main.commit={{.ShortCommit}}'"
      - "-X 'main.branch={{.Tag}}'"

  - id: lockerd
    main: ./cmd/lockerd/main.go
    binary: lockerd
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-X 'main.version={{.Version}}'"
      - "-X 'main.builddate={{.Date}}'"
      - "-X 'main.commit={{.ShortCommit}}'"
      - "-X 'main.branch={{.Tag}}'"

  - id: pam_locker
    main: ./cmd/module/main.go
    binary: pam_locker
    buildmode: c-shared
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    ldflags:
      - "-X 'main.version={{.Version}}'"
      - "-X 'main.builddate={{.Date}}'"
      - "-X 'main.commit={{.ShortCommit}}'"
      - "-X 'main.branch={{.Tag}}'"

archives:
  - formats: ['tar.gz']
    name_template: "{{ .ProjectName }}"
    files:
      - ./LICENSE
      - ./README.md
      - service/lockerd.service
      - config/config.yaml

changelog:
  sort: asc
