project_name: locker
version: 2

release:
  github:
    owner: bgrewell
    name: locker

builds:
  - id: locker
    main: ./cmd/locker/main.go
    binary: locker
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

  - id: lockerd
    main: ./cmd/lockerd/main.go
    binary: lockerd
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

  - id: pam_locker
    main: ./cmd/module/main.go
    binary: pam_locker
    buildmode: c-shared
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1

archives:
  - formats: ['tar.gz']
    name_template: >-
      {{ .ProjectName }}

    files:
      - ./LICENSE
      - ./README.md
      - service/lockerd.service
      - config/config.yaml

changelog:
  sort: asc
